### ISSUE TITLE
search the website with grover's algorithm

### ISSUE THREAD

**Issue by theRomanMercury** [qsharp-community/qsharp-community.github.io#23]
How can Grover's algorithm be applied to search the website?

**Comment by mertall** [comment]
search engines usually run with big data matrix decomposition and some pattern recognition within the matrix decomp.... How could you see grovers applied to this? I think a big question is then how can we turn classic information to quantum info, specifically connections between websites, if certain words are mentioned in one website/one website links to another/other features (PageRank is a great model to read about).

**Comment by theRomanMercury** [comment]
I do not know much about coding, but I have read that in a book (Supervised Learning with Quantum Computers), quantum machine learning can process classical data with quantum. I thought it was possible with this information and seeing the hybrid codes already available.

**Comment by mertall** [comment]
Yes you can definitely process classical data with quantum, though this is easier said than done, though when it is done it is quite cool. Usually vectors are created out of each sentence in a corpus of text in order to derive some sort of uniqueness/understanding. This would be interesting if we treated a sentence as a qubit. Though it should be noted that the recent innovations that came with NLP is due to a huge increase in power of classical computing. I feel we could make a quantum chatbot if we had a great deal of qubits at disposal, which is not the case at the moment.

**Comment by mertall** [comment]
have you seen hybrid codes for NLP models? if so please post it, I would love to learn!

**Comment by theRomanMercury** [comment]
I haven't done a research on NLP before, I'm thinking of looking. https://github.com/microsoft/MLADS2018-QuantumML this might be of interest to you.

**Comment by crazy4pi314** [comment]
> not know much about coding, but I have read that in a book (Supervised Learning with Quantum Computers), quantum machine learning can process classical data with quantum. I thought it was possible with this information and seeing the hybrid codes already available.

The hybrid code available that you could simulate would support only a couple of bits of classical data, way out of scope for any existing backends. 

> have you seen hybrid codes for NLP models? if so please post it, I would love to learn!

I can't vouch for the voracity of the content here, but there was a whole conference about quantum NLP:
https://www.youtube.com/channel/UCD5Pa5pKMRrkUSKGwjBxrSQ/featured

I think due to the scope of this task being a _long_ time out given the number of qubits needed, I'll close this for now.

**Comment by mertall** [comment]
Recently attended a lecture by Bob Coecke who specializes in Quantum NLP. Worth taking a look if it can take your vision into reality @theRomanMercury . Check out Picturing Quantum Processes: A First Course in Quantum Theory and Diagrammatic Reasoning https://www.amazon.com/dp/110710422X/ref=cm_sw_r_apan_glt_fabc_ASZHD5YQSGJJ3DDB4CG1

It should help with your task
